// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class CameraModel;
@class Item;
@class Label;
@class Labels;
@class Matrix;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - GrpcServiceRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface GrpcServiceRoot : GPBRootObject
@end

#pragma mark - Empty

@interface Empty : GPBMessage

@end

#pragma mark - Matrix

typedef GPB_ENUM(Matrix_FieldNumber) {
  Matrix_FieldNumber_Rows = 1,
  Matrix_FieldNumber_Cols = 2,
  Matrix_FieldNumber_DataArray = 3,
};

@interface Matrix : GPBMessage

@property(nonatomic, readwrite) uint32_t rows;

@property(nonatomic, readwrite) uint32_t cols;

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *dataArray;
/** The number of items in @c dataArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger dataArray_Count;

@end

#pragma mark - CameraModel

typedef GPB_ENUM(CameraModel_FieldNumber) {
  CameraModel_FieldNumber_Fx = 1,
  CameraModel_FieldNumber_Fy = 2,
  CameraModel_FieldNumber_Cx = 3,
  CameraModel_FieldNumber_Cy = 4,
};

@interface CameraModel : GPBMessage

@property(nonatomic, readwrite) float fx;

@property(nonatomic, readwrite) float fy;

@property(nonatomic, readwrite) float cx;

@property(nonatomic, readwrite) float cy;

@end

#pragma mark - Label

typedef GPB_ENUM(Label_FieldNumber) {
  Label_FieldNumber_DbId = 1,
  Label_FieldNumber_X = 2,
  Label_FieldNumber_Y = 3,
  Label_FieldNumber_Z = 4,
  Label_FieldNumber_Name = 5,
};

@interface Label : GPBMessage

@property(nonatomic, readwrite) uint32_t dbId;

/** 3D point x */
@property(nonatomic, readwrite) float x;

/** 3D point y */
@property(nonatomic, readwrite) float y;

/** 3D point z */
@property(nonatomic, readwrite) float z;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - Labels

typedef GPB_ENUM(Labels_FieldNumber) {
  Labels_FieldNumber_LabelsArray = 1,
};

@interface Labels : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Label*> *labelsArray;
/** The number of items in @c labelsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger labelsArray_Count;

@end

#pragma mark - Item

typedef GPB_ENUM(Item_FieldNumber) {
  Item_FieldNumber_Name = 1,
  Item_FieldNumber_X = 2,
  Item_FieldNumber_Y = 3,
  Item_FieldNumber_Size = 4,
};

/**
 * an identified item, for test purpose only
 **/
@interface Item : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 2D pixel x */
@property(nonatomic, readwrite) float x;

/** 2D pixel y */
@property(nonatomic, readwrite) float y;

@property(nonatomic, readwrite) float size;

@end

#pragma mark - LocalizationRequest

typedef GPB_ENUM(LocalizationRequest_FieldNumber) {
  LocalizationRequest_FieldNumber_RequestId = 1,
  LocalizationRequest_FieldNumber_Image = 2,
  LocalizationRequest_FieldNumber_Orientation = 3,
  LocalizationRequest_FieldNumber_Camera = 4,
};

@interface LocalizationRequest : GPBMessage

@property(nonatomic, readwrite) uint64_t requestId;

/** JPEG bytes */
@property(nonatomic, readwrite, copy, null_resettable) NSData *image;

/** JPEG EXIF orientation */
@property(nonatomic, readwrite) uint32_t orientation;

@property(nonatomic, readwrite, strong, null_resettable) CameraModel *camera;
/** Test to see if @c camera has been set. */
@property(nonatomic, readwrite) BOOL hasCamera;

@end

#pragma mark - LocalizationResponse

typedef GPB_ENUM(LocalizationResponse_FieldNumber) {
  LocalizationResponse_FieldNumber_RequestId = 1,
  LocalizationResponse_FieldNumber_Success = 2,
  LocalizationResponse_FieldNumber_DbId = 3,
  LocalizationResponse_FieldNumber_Pose = 4,
  LocalizationResponse_FieldNumber_ItemsArray = 5,
  LocalizationResponse_FieldNumber_Width = 6,
  LocalizationResponse_FieldNumber_Height = 7,
  LocalizationResponse_FieldNumber_Angle = 8,
  LocalizationResponse_FieldNumber_Width0 = 9,
  LocalizationResponse_FieldNumber_Height0 = 10,
};

@interface LocalizationResponse : GPBMessage

@property(nonatomic, readwrite) uint64_t requestId;

@property(nonatomic, readwrite) BOOL success;

@property(nonatomic, readwrite) uint32_t dbId;

@property(nonatomic, readwrite, strong, null_resettable) Matrix *pose;
/** Test to see if @c pose has been set. */
@property(nonatomic, readwrite) BOOL hasPose;

/** for test purpose only */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Item*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@property(nonatomic, readwrite) uint32_t width;

@property(nonatomic, readwrite) uint32_t height;

@property(nonatomic, readwrite) uint32_t angle;

@property(nonatomic, readwrite) double width0;

@property(nonatomic, readwrite) double height0;

@end

#pragma mark - GetLabelsResponse

typedef GPB_ENUM(GetLabelsResponse_FieldNumber) {
  GetLabelsResponse_FieldNumber_LabelsMap = 1,
};

@interface GetLabelsResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32ObjectDictionary<Labels*> *labelsMap;
/** The number of items in @c labelsMap without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger labelsMap_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
